INSERT INTO `actions` (`name`, `points`)
VALUES
('On-site course', 15),
('Online course', 9),
('Bootcamp', 20),
('Technical meetup / Monthly session', 6),
('Organized an internal competition', 12),
('Introductory event / Booth', 8),
('Partnership / Sponsorship', 15),
('Practical project / Product', 20),
('Participation in an external competition', 10),
('Published educational content', 10),
('Winning / First place externally', 18),
('On-site course attendance', 6),
('Online course attendance', 4),
('Bootcamp attending', 10),
('Attending a technical meetup / session', 3),
('Delivering a short session (≤ 20 minutes)', 8),
('Delivering a full course', 20),
('Organizing / volunteering in an event (per shift)', 5),
('Participating in a published practical project', 10),
('Participating in an external competition', 6),
('Qualifying to a top rank in a competition', 12),
('Winning First place externally', 18),
('Contributing to an approved design', 6),
('Writing an approved article / educational video', 10);