import logging

"""Admin CRUD for semesters.

A semester is described by its term, Hijri year and academic start year; the
Hijri code (471), Gregorian code (251) and name ("Fall 2025") are generated by
MySQL from those. There is no "current" flag to set - the current semester is
the most recent one that has started (see ``app/semesters.py``). Every mutation
best-effort resets the leaderboard app's cache so the change is visible there
immediately too.
"""

from datetime import date
from uuid import UUID

from fastapi import APIRouter, Depends, HTTPException, status
from sqlalchemy.orm import Session

from app.DB import club_structure as club_queries
from app.DB import semesters as semesters_queries
from app.DB.schema import Semesters, SemesterTerm

from app.exceptions import SemesterHasEvents, SemesterHasRoster, SemesterNotFound

from app.leaderboard_cache import reset_leaderboard_cache
from app.routers.models import BaseClassModel
from app.dependencies import DB
from app.semesters import current_semester

from app.routers.responses import DetailResponse
from app.services.permissions.catalogue import Perm
from app.services.permissions.guards import Require, Staff


logger = logging.getLogger(__name__)


router = APIRouter(prefix="/semesters", tags=["Semesters"])

# ============ models ============


class Semester_model(BaseClassModel):
    id: str
    term: SemesterTerm
    hijri_year: int
    academic_year_start: int
    hijri_code: int
    gregorian_code: int
    name: str
    start_date: date
    end_date: date
    is_public: bool
    # Computed from the calendar on every read, never stored.
    is_current: bool


class SemesterInput_model(BaseClassModel):
    term: SemesterTerm
    hijri_year: int
    academic_year_start: int
    start_date: date
    end_date: date
    # No default: omitting this would silently flip a private semester back to public.
    is_public: bool


# ============ helpers ============


def _validate(session: Session, payload: SemesterInput_model, exclude_id: str | None = None) -> None:
    if payload.end_date < payload.start_date:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST, detail="End date must be on or after the start date"
        )
    if not 1400 <= payload.hijri_year <= 1499:
        raise HTTPException(status_code=status.HTTP_400_BAD_REQUEST, detail="Hijri year must be between 1400 and 1499")
    if not 2000 <= payload.academic_year_start <= 2099:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST, detail="Academic start year must be between 2000 and 2099"
        )

    clash = semesters_queries.get_term_conflict(
        session, payload.term, payload.hijri_year, payload.academic_year_start, exclude_id
    )
    if clash is not None:
        raise HTTPException(
            status_code=status.HTTP_409_CONFLICT,
            detail=f"{clash.name} ({clash.hijri_code} / {clash.gregorian_code}) already uses this term and year",
        )

    overlapping = semesters_queries.get_overlapping_semesters(session, payload.start_date, payload.end_date, exclude_id)
    if overlapping:
        names = ", ".join(semester.name for semester in overlapping)
        raise HTTPException(status_code=status.HTTP_409_CONFLICT, detail=f"The dates overlap with {names}")


def _to_model(semester: Semesters, current: Semesters | None) -> Semester_model:
    return Semester_model.model_validate(
        {
            **{column: getattr(semester, column) for column in Semester_model.model_fields if column != "is_current"},
            "is_current": current is not None and current.id == semester.id,
        }
    )


def _get_or_404(session: Session, semester_id: UUID) -> Semesters:
    semester = semesters_queries.get_semester_by_id(session, str(semester_id))
    if semester is None:
        raise SemesterNotFound(str(semester_id))
    return semester


def _reset_cache_best_effort() -> None:
    """The leaderboard app caches semester-scoped data; nudge it after a change."""
    try:
        reset_leaderboard_cache()
        logger.info("Leaderboard cache reset triggered after semester change")
    except Exception as cache_err:
        logger.error(cache_err)


# ============ routes ============


@router.get("", status_code=status.HTTP_200_OK, response_model=list[Semester_model], dependencies=[Depends(Staff)])
def get_all_semesters(session: DB):
    current = current_semester(session)
    return [_to_model(semester, current) for semester in semesters_queries.get_semesters(session)]


@router.post(
    "",
    status_code=status.HTTP_201_CREATED,
    response_model=Semester_model,
    dependencies=[Depends(Require(Perm.SEMESTERS_MANAGE))],
)
def create_semester(payload: SemesterInput_model, session: DB):
    _validate(session, payload)
    semester = semesters_queries.create_semester(session, **payload.model_dump())
    session.commit()
    logger.info(f"Created semester [{semester.hijri_code}] {semester.name} {semester.start_date} → {semester.end_date}")
    result = _to_model(semester, current_semester(session))
    _reset_cache_best_effort()
    return result


@router.put(
    "/{semester_id}",
    status_code=status.HTTP_200_OK,
    response_model=Semester_model,
    dependencies=[Depends(Require(Perm.SEMESTERS_MANAGE))],
)
def update_semester(semester_id: UUID, payload: SemesterInput_model, session: DB):
    semester = _get_or_404(session, semester_id)
    _validate(session, payload, exclude_id=semester.id)
    semesters_queries.update_semester(session, semester, **payload.model_dump())
    session.commit()
    logger.info(f"Updated semester [{semester.hijri_code}] {semester.start_date} → {semester.end_date}")
    result = _to_model(semester, current_semester(session))
    _reset_cache_best_effort()
    return result


@router.delete(
    "/{semester_id}",
    status_code=status.HTTP_200_OK,
    dependencies=[Depends(Require(Perm.SEMESTERS_MANAGE))],
    response_model=DetailResponse,
)
def delete_semester(semester_id: UUID, session: DB):
    semester = _get_or_404(session, semester_id)
    event_count = semesters_queries.count_semester_events(session, semester.id)
    if event_count:
        raise SemesterHasEvents(semester.name, event_count)
    if club_queries.semester_has_memberships(session, semester.id):
        raise SemesterHasRoster(semester.name)

    semesters_queries.delete_semester(session, semester)
    session.commit()
    logger.info(f"Deleted semester [{semester.hijri_code}] {semester.name}")
    _reset_cache_best_effort()
    return {"detail": "Semester deleted successfully"}
